openapi: 3.1.2
info:
  title: Arduino Thermo Hygrometer API.
  description: A Java Web API for an Arduino Thermo Hygrometer IoT device.
  contact:
    name: Burhan Mohammad Sarfraz
    email: burhan.mohammad.sarfraz@outlook.com
  license:
    name: MIT license
    url: https://mit-license.org/
  version: 1.0.0-SNAPSHOT

servers:
  - url: http://{host}:{port}
    description: Local development server.
    variables:
      host:
        default: localhost
        enum: [ localhost ]
      port:
        default: "5000"
        enum: [ "5000" ]

tags:
  - name: Battery
    description: Battery status of Arduino device.
  - name: Temperature
    description: Measured temperature by Arduino device.
  - name: Humidity
    description: Measured humidity by Arduino device.

paths:
  /api/v1/batteries:
    get:
      tags:
        - Battery
      summary: Retrieve a battery by date or timestamp.
      description: Retrieves the battery status of the Arduino device by date or timestamp.
      operationId: getBatteriesByDateOrTimestamp
      parameters:
        - $ref: "#/components/parameters/DateTimeParam"
        - $ref: "#/components/parameters/CheckOnlyDateParam"
      responses:
        "200":
          description: Battery found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BatteryDto"
              examples:
                battery:
                  $ref: "#/components/examples/ExampleBattery"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    delete:
      tags:
        - Battery
      summary: Delete battery by date or timestamp.
      description: Deletes the battery status of the Arduino device by date or timestamp.
      operationId: deleteBatteriesByDateOrTimestamp
      parameters:
        - $ref: "#/components/parameters/DateTimeParam"
        - $ref: "#/components/parameters/CheckOnlyDateParam"
      responses:
        "204":
          description: Battery deleted.
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    post:
      tags:
        - Battery
      summary: Create remaining battery.
      description: Registers the remaining battery status of the Arduino device.
      operationId: createBattery
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatteryDto"
            examples:
              battery:
                $ref: "#/components/examples/ExampleBattery"
        required: true
      responses:
        "201":
          description: Battery created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatteryDto"
              examples:
                battery:
                  $ref: "#/components/examples/ExampleBattery"
        "400":
          $ref: "#/components/responses/ProblemDetailResponse"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"

  /api/v1/batteries/{id}:
    get:
      tags:
        - Battery
      summary: Retrieve a battery by id.
      description: Retrieves the battery status of the Arduino device by id.
      operationId: getBatteryById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Battery found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatteryDto"
              examples:
                battery:
                  $ref: "#/components/examples/ExampleBattery"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    delete:
      tags:
        - Battery
      summary: Delete battery by id.
      description: Deletes the battery status of the Arduino device by id.
      operationId: deleteBatteryById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "204":
          description: Battery deleted.
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"

  /api/v1/humidities:
    get:
      tags:
        - Humidity
      summary: Retrieve measured humidity by date or timestamp.
      description: Retrieves the measured humidity from the Arduino device by date or timestamp.
      operationId: getHumiditiesByDateOrTimestamp
      parameters:
        - $ref: "#/components/parameters/DateTimeParam"
        - $ref: "#/components/parameters/CheckOnlyDateParam"
      responses:
        "200":
          description: Humidity found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HumidityDto"
              examples:
                humidity:
                  $ref: "#/components/examples/ExampleHumidity"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    delete:
      tags:
        - Humidity
      summary: Delete measured humidity by date or timestamp.
      description: Deletes the measured humidity from the Arduino device by date or timestamp.
      operationId: deleteHumiditiesByDateOrTimestamp
      parameters:
        - $ref: "#/components/parameters/DateTimeParam"
        - $ref: "#/components/parameters/CheckOnlyDateParam"
      responses:
        "204":
          description: Humidity deleted.
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    post:
      tags:
        - Humidity
      summary: Create measured humidity.
      description: Registers the measured humidity from the Arduino device.
      operationId: createHumidity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HumidityDto"
            examples:
              humidity:
                $ref: "#/components/examples/ExampleHumidity"
        required: true
      responses:
        "201":
          description: Humidity created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumidityDto"
              examples:
                humidity:
                  $ref: "#/components/examples/ExampleHumidity"
        "400":
          $ref: "#/components/responses/ProblemDetailResponse"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"

  /api/v1/humidities/{id}:
    get:
      tags:
        - Humidity
      summary: Retrieve measured humidity by id.
      description: Retrieves the measured humidity from the Arduino device by id.
      operationId: getHumidityById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Humidity found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumidityDto"
              examples:
                humidity:
                  $ref: "#/components/examples/ExampleHumidity"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    delete:
      tags:
        - Humidity
      summary: Delete measured humidity by id.
      description: Deletes the measured humidity from the Arduino device by id.
      operationId: deleteHumidityById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "204":
          description: Humidity deleted.
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"

  /api/v1/temperatures:
    get:
      tags:
        - Temperature
      summary: Retrieve measured temperature by date or timestamp.
      description: Retrieves the measured temperature from the Arduino device by date or timestamp.
      operationId: getTemperaturesByDateOrTimestamp
      parameters:
        - $ref: "#/components/parameters/DateTimeParam"
        - $ref: "#/components/parameters/CheckOnlyDateParam"
      responses:
        "200":
          description: Temperature found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TemperatureDto"
              examples:
                temperature:
                  $ref: "#/components/examples/ExampleTemperature"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    delete:
      tags:
        - Temperature
      summary: Delete measured temperature by date or timestamp.
      description: Deletes the measured temperature from the Arduino device by date or timestamp.
      operationId: deleteTemperaturesByDateOrTimestamp
      parameters:
        - $ref: "#/components/parameters/DateTimeParam"
        - $ref: "#/components/parameters/CheckOnlyDateParam"
      responses:
        "204":
          description: Temperature deleted.
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    post:
      tags:
        - Temperature
      summary: Create measured temperature.
      description: Registers the measured temperature from the Arduino device.
      operationId: createTemperature
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemperatureDto"
            examples:
              temperature:
                $ref: "#/components/examples/ExampleTemperature"
        required: true
      responses:
        "201":
          description: Temperature created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemperatureDto"
              examples:
                temperature:
                  $ref: "#/components/examples/ExampleTemperature"
        "400":
          $ref: "#/components/responses/ProblemDetailResponse"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"

  /api/v1/temperatures/{id}:
    get:
      tags:
        - Temperature
      summary: Retrieve measured temperature by id.
      description: Retrieves the measured temperature from the Arduino device by id.
      operationId: getTemperatureById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Temperature found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemperatureDto"
              examples:
                temperature:
                  $ref: "#/components/examples/ExampleTemperature"
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"
    delete:
      tags:
        - Temperature
      summary: Delete measured temperature by id.
      description: Deletes the measured temperature from the Arduino device by id.
      operationId: deleteTemperatureById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "204":
          description: Temperature deleted.
        "403":
          $ref: "#/components/responses/ProblemDetailResponse"
        "404":
          $ref: "#/components/responses/ProblemDetailResponse"

components:
  examples:
    ExampleBattery:
      description: Example of Battery object.
      value:
        registeredAt: "2017-07-21T17:00:00Z"
        batteryStatus: 50

    ExampleHumidity:
      description: Example of Humidity object.
      value:
        registeredAt: "2017-07-21T17:00:00Z"
        airHumidity: 70.00

    ExampleTemperature:
      description: Example of Temperature object.
      value:
        registeredAt: "2017-07-21T17:00:00Z"
        temp: 70.00

  parameters:
    IdParam:
      in: path
      name: id
      required: true
      schema:
        type: string
        format: uuid
        example: "86644f52-f3d4-4285-9f2f-4d2ee4c15035"

    DateTimeParam:
      in: query
      name: dateTime
      required: true
      schema:
        type: string
        format: date-time
        example: "2017-07-21T17:00:00Z"

    CheckOnlyDateParam:
      in: query
      name: checkOnlyDate
      required: true
      schema:
        type: boolean
        default: false
        example: false

  responses:
    ProblemDetailResponse:
      description: Problem detail error response.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"

  schemas:
    ProblemDetail:
      description: A tailored problem details schema, respecting the RFC `https://www.rfc-editor.org/rfc/rfc9457`.
      type: object
      properties:
        type:
          description: A URI identifying the problem type.
          type: string
          example: "https://example.com/problems/resource-not-found"
        title:
          description: A short, human-readable summary of the problem (not localized).
          type: string
          example: "Resource not found."
        detail:
          description: A human-readable explanation specific to this occurrence of the problem (not localized).
          type: string
          example: "Resource with id 00000000-0000-0000-0000-000000000000 not found."
        status:
          description: The HTTP status code for the request with the problem.
          type: integer
          example: 404
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          type: string
          example: "/api/v1/batteries/{id}"
        traceId:
          description: A unique identifier used to correlate logs and diagnostics.
          type: string
          example: "00-80e7f8c9f3b2a14d9c1e4b2d9f9c1234-91f3a2b1c4d5e6f7-00"
        timestamp:
          description: The time at which the error occurred.
          type: string
          format: date-time
          example: "2017-07-21T17:00:00Z"
        errors:
          description: A collection of validation errors. Occurs only during validation failures.
          type: array
          items:
            $ref: "#/components/schemas/ProblemDetailsValidationError"
      required:
        - type
        - title
        - detail
        - status
        - instance
        - traceId
        - timestamp
    
    ProblemDetailsValidationError:
      description: Includes details about validation errors.
      type: object
      properties:
        description:
          description: Non-localized description of the error.
          type: string
        parameter:
          description: Included to identify a path or query parameter that is invalid.
          type: string
          nullable: true
        header:
          description: Included to identify a header parameter that is invalid.
          type: string
          nullable: true
        pointer:
          description: Identifies a property of a JSON payload that is invalid, following RFC `https://www.rfc-editor.org/rfc/rfc6901`.
          type: string
          nullable: true
      required:
        - description
        - parameter
        - header
        - pointer

    BatteryDto:
      type: object
      properties:
        id:
          description: Id of object with remaining battery percentage of the Arduino device.
          type: string
          format: uuid
          readOnly: true
          example: "86644f52-f3d4-4285-9f2f-4d2ee4c15035"
        registeredAt:
          description: Registration time of the remaining battery percentage of the Arduino device.
          type: string
          format: date-time
          example: "2017-07-21T17:00:00Z"
        batteryStatus:
          description: Remaining battery percentage of the Arduino device.
          type: integer
          format: int32
          minimum: 0
          maximum: 100
          example: 70
      required:
        - registeredAt
        - batteryStatus

    HumidityDto:
      type: object
      properties:
        id:
          description: Id of object with measured air humidity by the Arduino device.
          type: string
          format: uuid
          readOnly: true
          example: "86644f52-f3d4-4285-9f2f-4d2ee4c15035"
        registeredAt:
          description: Registration time of measured air humidity by the Arduino device.
          type: string
          format: date-time
          example: "2017-07-21T17:00:00Z"
        airHumidity:
          description: Measured air humidity by the Arduino device.
          type: number
          format: double
          minimum: 20.00
          maximum: 90.00
          example: 70.00
      required:
        - registeredAt
        - airHumidity

    TemperatureDto:
      type: object
      properties:
        id:
          description: Id of object with measured temperature by the Arduino device.
          type: string
          format: uuid
          readOnly: true
          example: "86644f52-f3d4-4285-9f2f-4d2ee4c15035"
        registeredAt:
          description: Registration time of measured temperature by the Arduino device.
          type: string
          format: date-time
          example: "2017-07-21T17:00:00Z"
        temp:
          description: Measured temperature by the Arduino device.
          type: number
          format: double
          minimum: -55.00
          maximum: 125.00
          example: 70.00
      required:
        - registeredAt
        - temp
  
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

security:
  - ApiKeyAuth: [ ]
