openapi: 3.1.2
info:
  title: Arduino Thermo Hygrometer API.
  description: A Java Web API for an Arduino Thermo Hygrometer IoT device.
  contact:
    name: Burhan Mohammad Sarfraz
    email: burhan.mohammad.sarfraz@outlook.com
  license:
    name: MIT license
    url: https://mit-license.org/
  version: 1.0.0-SNAPSHOT

servers:
  - url: http://localhost:5000
    description: Local development server.

tags:
  - name: Battery.
    description: Battery status of arduino device.
  - name: Temperature.
    description: Measured temperature by arduino device.
  - name: Humidity.
    description: Measured humidity by arduino device.

paths:
  /api/batteries:
    get:
      tags:
        - Battery.
      summary: Retrieve a battery by date or timestamp.
      operationId: getBatteryByDateOrTimestamp
      requestBody:
        content:
          applicatjon/json:
            schema:
              $ref: "#/components/schemas/DateTimeRequest"
        required: true
      responses:
        "200":
          description: Battery found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BatteryDto"
              examples:
                battery:
                  $ref: "#/components/examples/ExampleBattery"
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    delete:
      tags:
        - Battery.
      summary: Delete battery by date or timestamp.
      operationId: deleteBatteryByDateOrTimestamp
      requestBody:
        content:
          applicatjon/json:
            schema:
              $ref: "#/components/schemas/DateTimeRequest"
        required: true
      responses:
        "204":
          description: Battery deleted.
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    post:
      tags:
        - Battery.
      summary: Create remaining battery.
      operationId: createBattery
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatteryDto"
            examples:
              battery:
                $ref: "#/components/examples/ExampleBattery"
        required: true
      responses:
        "201":
          description: Battery created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatteryDto"
              examples:
                battery:
                  $ref: "#/components/examples/ExampleBattery"
        "400":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/BadRequest"

  /api/batteries/{id}:
    get:
      tags:
        - Battery.
      summary: Retrieve a battery by id.
      operationId: getBatteryById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Battery found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatteryDto"
              examples:
                battery:
                  $ref: "#/components/examples/ExampleBattery"
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    delete:
      tags:
        - Battery.
      summary: Delete battery by id.
      operationId: deleteBatteryDtoById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "204":
          description: Battery deleted.
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"

  /api/humidities:
    get:
      tags:
        - Humidity.
      summary: Retrieve measured humidity by date or timestamp.
      operationId: getHumidityByDateOrTimestamp
      requestBody:
        content:
          applicatjon/json:
            schema:
              $ref: "#/components/schemas/DateTimeRequest"
        required: true
      responses:
        "200":
          description: Humidity found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HumidityDto"
              examples:
                humidity:
                  $ref: "#/components/examples/ExampleHumidity"
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    delete:
      tags:
        - Humidity.
      summary: Delete measured humidity by date or timestamp.
      operationId: deleteHumidityByDateOrTimestamp
      requestBody:
        content:
          applicatjon/json:
            schema:
              $ref: "#/components/schemas/DateTimeRequest"
        required: true
      responses:
        "204":
          description: Humidity deleted.
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    post:
      tags:
        - Humidity.
      summary: Create measured humidity.
      operationId: createHumidity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HumidityDto"
            examples:
              humidity:
                $ref: "#/components/examples/ExampleHumidity"
        required: true
      responses:
        "201":
          description: Humidity created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumidityDto"
              examples:
                humidity:
                  $ref: "#/components/examples/ExampleHumidity"
        "400":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/BadRequest"

  /api/humidities/{id}:
    get:
      tags:
        - Humidity.
      summary: Retrieve measured humidity by id.
      operationId: getHumidityById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Humidity found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumidityDto"
              examples:
                humidity:
                  $ref: "#/components/examples/ExampleHumidity"
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    delete:
      tags:
        - Humidity.
      summary: Delete measured humidity by id.
      operationId: deleteHumidityDtoById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "204":
          description: Humidity deleted.
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"

  /api/temperatures:
    get:
      tags:
        - Temperature.
      summary: Retrieve measured temperature by date or timestamp.
      operationId: getTemperatureByDateOrTimestamp
      requestBody:
        content:
          applicatjon/json:
            schema:
              $ref: "#/components/schemas/DateTimeRequest"
        required: true
      responses:
        "200":
          description: Temperature found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TemperatureDto"
              examples:
                temperature:
                  $ref: "#/components/examples/ExampleTemperature"
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    delete:
      tags:
        - Temperature.
      summary: Delete measured temperature by date or timestamp.
      operationId: deleteTemperatureByDateOrTimestamp
      requestBody:
        content:
          applicatjon/json:
            schema:
              $ref: "#/components/schemas/DateTimeRequest"
        required: true
      responses:
        "204":
          description: Temperature deleted.
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    post:
      tags:
        - Temperature.
      summary: Create measured temperature.
      operationId: createTemperature
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemperatureDto"
            examples:
              temperature:
                $ref: "#/components/examples/ExampleTemperature"
        required: true
      responses:
        "201":
          description: Temperature created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemperatureDto"
              examples:
                temperature:
                  $ref: "#/components/examples/ExampleTemperature"
        "400":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/BadRequest"

  /api/temperatures/{id}:
    get:
      tags:
        - Temperature.
      summary: Retrieve measured temperature by id.
      operationId: getTemperatureById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Temperature found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemperatureDto"
              examples:
                temperature:
                  $ref: "#/components/examples/ExampleTemperature"
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"
    delete:
      tags:
        - Temperature.
      summary: Delete measured temperature by id.
      operationId: deleteTemperatureDtoById
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "204":
          description: Temperature deleted.
        "404":
          $ref: "https://api.swaggerhub.com/domains/smartbear-public/ProblemDetails/1.0.0#/components/responses/NotFound"

components:
  examples:
    ExampleTemperature:
      description: Example of Temperature object.
      value:
        registeredAt: "2017-07-21T17:32:28Z"
        temp: 70.00

    ExampleHumidity:
      description: Example of Humidity object.
      value:
        registeredAt: "2017-07-21T17:32:28Z"
        airHumidity: 70.00

    ExampleBattery:
      description: Example of Battery object.
      value:
        registeredAt: "2017-07-21T17:32:28Z"
        batteryStatus: 50

  parameters:
    IdParam:
      in: path
      name: id
      description: Identifier for measured temperature.
      required: true
      schema:
        type: string
        format: uuid
        example: "86644f52-f3d4-4285-9f2f-4d2ee4c15035"

  schemas:
    DateTimeRequest:
      type: object
      properties:
        dateTime:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        checkOnlyDate:
          type: boolean
          example: true
      required:
        - dateTime
        - checkOnlyDate

    TemperatureDto:
      type: object
      properties:
        registeredAt:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        temp:
          type: number
          format: double
          minimum: -55.00
          maximum: 125.00
          example: 100.00
      required:
        - registeredAt
        - temp

    HumidityDto:
      type: object
      properties:
        registeredAt:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        airHumidity:
          type: number
          format: double
          minimum: 20.00
          maximum: 90.00
          example: 70.00
      required:
        - registeredAt
        - airHumidity

    BatteryDto:
      type: object
      properties:
        registeredAt:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        batteryStatus:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
          example: 50
      required:
        - registeredAt
        - batteryStatus
