spring:
  profiles:
    active: local
  application:
    group: api
    name: api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres-local
    password: postgres-local
    url: jdbc:postgresql://localhost:5432/arduinothermohygrometer-local
  flyway:
    enabled: true
    baseline-on-migrate: true
    connect-retries: 3
    locations: classpath:db/migrations, classpath:db/undo_migrations
  mvc:
    apiversion:
      default: v1
      use:
        path-segment: 0

server:
  port: 5000

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  packages-to-scan: api.arduinothermohygrometer
  swagger-ui:
    path: /v1/swagger
    operations-sorter: method

info:
  contact:
    name: Burhan Mohammad Sarfraz
    email: burhan.mohammad.sarfraz@outlook.com
  description: A Java Web API for an Arduino Thermo Hygrometer IoT device.
  license:
    name: MIT license
    url: https://mit-license.org/
  title: Arduino Thermo Hygrometer API.
  version: "@project.version@"

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"