cors:
  allowed-headers: [ Accept, Content-Type, X-API-KEY ]
  allowed-methods: [ GET, POST ]
  allowed-origins: http://localhost

info:
  contact:
    name: Burhan Mohammad Sarfraz
    email: burhan.mohammad.sarfraz@outlook.com
  description: A Java Web API for an Arduino Thermo Hygrometer IoT device.
  license:
    name: MIT license
    url: https://mit-license.org/
  title: Arduino Thermo Hygrometer API.
  version: 1.0.0-SNAPSHOT

management:
  health:
    rabbit:
      enabled: false
  endpoint:
    health:
      show-components: when_authorized
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "health,info"

security:
  api-key: "api-key-secret"
  api-header: X-API-KEY
  api-role: ROLE_API
  api-scheme-name: ApiKeyAuth

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: api.arduinothermohygrometer
  swagger-ui:
    enabled: true
    operations-sorter: method
    path: /swagger-ui.html