cors:
  allowed-headers: [ Accept, Content-Type, X-API-KEY ]
  allowed-methods: [ GET, DELETE, POST ]
  allowed-origins: http://localhost

info:
  contact:
    name: Burhan Mohammad Sarfraz
    email: burhan.mohammad.sarfraz@outlook.com
  description: A Java Web API for an Arduino Thermo Hygrometer IoT device.
  license:
    name: MIT license
    url: https://mit-license.org/
  title: Arduino Thermo Hygrometer API.
  version: 1.0.0-SNAPSHOT

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-components: when_authorized
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health, info, metrics

security:
  api-key: "api-secret-key"
  api-header-name: X-API-KEY
  api-roles: [ API_ADMIN, ACTUATOR ]
  api-scheme-name: ApiKeyAuth

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres-local
    password: postgres-local
    url: jdbc:postgresql://localhost:5432/arduinothermohygrometer-local
  mvc:
    problemdetails:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
    path: /swagger-ui.html
  servers:
    - url: http://localhost:5000
      description: Local development server.