server:
  port: 5000

spring:
  profiles:
    active: local
  application:
    group: api
    name: api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres-local
    password: postgres-local
    url: jdbc:postgresql://localhost:5432/arduinothermohygrometer-local
  flyway:
    baseline-on-migrate: true
    connect-retries: 3
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: api.arduinothermohygrometer
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html

cors:
  allowedOrigins: http://localhost:3000

info:
  contact:
    name: Burhan Mohammad Sarfraz
    email: burhan.mohammad.sarfraz@outlook.com
  description: A Java Web API for an Arduino Thermo Hygrometer IoT device.
  license:
    name: MIT license
    url: https://mit-license.org/
  title: Arduino Thermo Hygrometer API.
  version: ${build.version}

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"