spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres-local
    password: postgres-local
    url: jdbc:postgresql://localhost:5432/arduinothermohygrometer-local

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
    path: /swagger-ui.html
  servers:
    - url: http://{host}:{port}
      description: Development server.
      variables:
        host:
          default: localhost
          enum: [ localhost ]
        port:
          default: 5000
          enum: [ 5000 ]