/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a JWT access token.
         * @description Exchanges configured client credentials for a short-lived JWT access token.
         */
        post: operations["issueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batteries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a battery by date or timestamp.
         * @description Retrieves the battery status of the Arduino device by date or timestamp. The dateOnly parameter can be used to retrieve the battery status for a specific date, ignoring the time section of the registeredAt parameter.
         */
        get: operations["getBatteriesByDateOrTimestamp"];
        put?: never;
        /**
         * Create remaining battery.
         * @description Registers the remaining battery status of the Arduino device.
         */
        post: operations["createBattery"];
        /**
         * Delete battery by date or timestamp.
         * @description Deletes the battery status of the Arduino device by date or timestamp. The dateOnly parameter can be used to delete all the battery statuses for a specific date, or delete the battery status for a specific timestamp.
         */
        delete: operations["deleteBatteriesByDateOrTimestamp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/humidities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve measured humidity by date or timestamp.
         * @description Retrieves the measured humidity from the Arduino device by date or timestamp. The dateOnly parameter can be used to retrieve the measured humidity for a specific date, ignoring the time section of the registeredAt parameter.
         */
        get: operations["getHumiditiesByDateOrTimestamp"];
        put?: never;
        /**
         * Create measured humidity.
         * @description Registers the measured humidity from the Arduino device.
         */
        post: operations["createHumidity"];
        /**
         * Delete measured humidity by date or timestamp.
         * @description Deletes the measured humidity from the Arduino device by date or timestamp. The dateOnly parameter can be used to delete all the measured humidities for a specific date, or delete the measured humidity for a specific timestamp.
         */
        delete: operations["deleteHumiditiesByDateOrTimestamp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/temperatures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve measured temperature by date or timestamp.
         * @description Retrieves the measured temperature from the Arduino device by date or timestamp. The dateOnly parameter can be used to retrieve the measured temperature for a specific date, ignoring the time section of the registeredAt parameter.
         */
        get: operations["getTemperaturesByDateOrTimestamp"];
        put?: never;
        /**
         * Create measured temperature.
         * @description Registers the measured temperature from the Arduino device.
         */
        post: operations["createTemperature"];
        /**
         * Delete measured temperature by date or timestamp.
         * @description Deletes the measured temperature from the Arduino device by date or timestamp. The dateOnly parameter can be used to delete all the measured temperatures for a specific date, or delete the measured temperature for a specific timestamp.
         */
        delete: operations["deleteTemperaturesByDateOrTimestamp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Problem details, respecting RFC 9457. */
        ProblemDetailsDto: {
            /**
             * @description A URI identifying the problem type.
             * @example https://example.com/problems/resource-not-found
             */
            type: string;
            /**
             * @description A short, human-readable summary of the problem.
             * @example Resource not found.
             */
            title: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Resources not found for date 2017-07-21.
             */
            detail: string;
            /**
             * @description The HTTP status code for the request with the problem.
             * @example 404
             */
            status: number;
            /**
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example /api/v1/batteries?registeredAt=2017-07-21T17:00:00Z&dateOnly=true
             */
            instance: string;
            /**
             * @description A unique identifier used to correlate logs and diagnostics.
             * @example 00-80e7f8c9f3b2a14d9c1e4b2d9f9c1234-91f3a2b1c4d5e6f7-00
             */
            traceId: string;
            /**
             * Format: date-time
             * @description The time at which the error occurred.
             * @example 2017-07-21T17:00:00Z
             */
            timestamp: string;
            /** @description A collection of validation errors. Occurs only during validation failures. */
            errors?: components["schemas"]["ProblemDetailsValidationErrorDto"][];
        };
        /** @description Problem details, including details about validation errors. */
        ProblemDetailsValidationErrorDto: {
            /**
             * @description Non-localized description of the error.
             * @example Must not be null.
             */
            description: string;
            /**
             * @description Included to identify a path or query parameter that is invalid.
             * @example registeredAt
             */
            parameter?: string | null;
            /**
             * @description Included to identify a header parameter that is invalid.
             * @example Authorization
             */
            header?: string | null;
            /**
             * @description Identifies a JSON property that is invalid, RFC `https://www.rfc-editor.org/rfc/rfc6901`.
             * @example /batteryStatus
             */
            pointer?: string | null;
        };
        /** @description Metadata about a battery object. */
        BatteryDto: {
            /**
             * Format: date-time
             * @description Registration time of the remaining battery percentage of the Arduino device.
             * @example 2017-07-21T17:00:00Z
             */
            registeredAt: string;
            /**
             * Format: int32
             * @description Remaining battery percentage of the Arduino device.
             */
            batteryStatus: number;
        };
        /** @description Metadata about a humidity object. */
        HumidityDto: {
            /**
             * Format: date-time
             * @description Registration time of measured air humidity by the Arduino device.
             * @example 2017-07-21T17:00:00Z
             */
            registeredAt: string;
            /**
             * Format: double
             * @description Measured air humidity by the Arduino device. The air humidity can be between 20.00 and 90.00, where 20.00 means the air is very dry and 90.00 means the air is very humid.
             */
            airHumidity: number;
        };
        /** @description Metadata about a temperature object. */
        TemperatureDto: {
            /**
             * Format: date-time
             * @description Registration time of measured temperature by the Arduino device.
             * @example 2017-07-21T17:00:00Z
             */
            registeredAt: string;
            /**
             * Format: double
             * @description Measured temperature by the Arduino device. The temperature can be between -55.00 and 125.00, where -55.00 means the temperature is extremely cold and 125.00 means the temperature is extremely hot.
             */
            temp: number;
        };
        /** @description Credentials used to obtain a JWT access token. */
        JwtTokenDto: {
            username: string;
            /** Format: password */
            password: string;
        };
        /** @description JWT access token response. */
        JwtTokenResponse: {
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /**
             * Format: int64
             * @description Lifetime of the access token in seconds.
             */
            expiresIn: number;
        };
    };
    responses: {
        /** @description Error response in the shape of a Problem details object. */
        ProblemDetailsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetailsDto"];
            };
        };
        /** @description Error response for a Too Many Requests error. */
        TooManyRequestsResponse: {
            headers: {
                "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetailsDto"];
            };
        };
    };
    parameters: {
        /** @description Date and time of registered sensor readings from the Arduino device. */
        RegisteredAt: string;
        /** @description Only use the date section of registered sensor readings from the Arduino device (registeredAt parameter). */
        DateOnly: boolean;
    };
    requestBodies: never;
    headers: {
        /** @description Maximum number of requests allowed. */
        "X-RateLimit-Limit": number;
        /** @description Remaining requests. */
        "X-RateLimit-Remaining": number;
        /** @description Unix timestamp when the number of request resets. */
        "X-RateLimit-Reset": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JwtTokenDto"];
            };
        };
        responses: {
            /** @description JWT access token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JwtTokenResponse"];
                };
            };
            /** @description Bad Request. */
            400: components["responses"]["ProblemDetailsResponse"];
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
        };
    };
    getBatteriesByDateOrTimestamp: {
        parameters: {
            query: {
                /** @description Date and time of registered sensor readings from the Arduino device. */
                registeredAt: components["parameters"]["RegisteredAt"];
                /** @description Only use the date section of registered sensor readings from the Arduino device (registeredAt parameter). */
                dateOnly: components["parameters"]["DateOnly"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Battery found. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatteryDto"][];
                };
            };
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    createBattery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatteryDto"];
            };
        };
        responses: {
            /** @description Battery created. */
            201: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatteryDto"];
                };
            };
            /** @description Bad Request. */
            400: components["responses"]["ProblemDetailsResponse"];
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    deleteBatteriesByDateOrTimestamp: {
        parameters: {
            query: {
                /** @description Date and time of registered sensor readings from the Arduino device. */
                registeredAt: components["parameters"]["RegisteredAt"];
                /** @description Only use the date section of registered sensor readings from the Arduino device (registeredAt parameter). */
                dateOnly: components["parameters"]["DateOnly"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Battery deleted. */
            204: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    getHumiditiesByDateOrTimestamp: {
        parameters: {
            query: {
                /** @description Date and time of registered sensor readings from the Arduino device. */
                registeredAt: components["parameters"]["RegisteredAt"];
                /** @description Only use the date section of registered sensor readings from the Arduino device (registeredAt parameter). */
                dateOnly: components["parameters"]["DateOnly"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Humidity found. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumidityDto"][];
                };
            };
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    createHumidity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumidityDto"];
            };
        };
        responses: {
            /** @description Humidity created. */
            201: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumidityDto"];
                };
            };
            /** @description Bad Request. */
            400: components["responses"]["ProblemDetailsResponse"];
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    deleteHumiditiesByDateOrTimestamp: {
        parameters: {
            query: {
                /** @description Date and time of registered sensor readings from the Arduino device. */
                registeredAt: components["parameters"]["RegisteredAt"];
                /** @description Only use the date section of registered sensor readings from the Arduino device (registeredAt parameter). */
                dateOnly: components["parameters"]["DateOnly"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Humidity deleted. */
            204: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    getTemperaturesByDateOrTimestamp: {
        parameters: {
            query: {
                /** @description Date and time of registered sensor readings from the Arduino device. */
                registeredAt: components["parameters"]["RegisteredAt"];
                /** @description Only use the date section of registered sensor readings from the Arduino device (registeredAt parameter). */
                dateOnly: components["parameters"]["DateOnly"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temperature found. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemperatureDto"][];
                };
            };
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    createTemperature: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemperatureDto"];
            };
        };
        responses: {
            /** @description Temperature created. */
            201: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemperatureDto"];
                };
            };
            /** @description Bad Request. */
            400: components["responses"]["ProblemDetailsResponse"];
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
    deleteTemperaturesByDateOrTimestamp: {
        parameters: {
            query: {
                /** @description Date and time of registered sensor readings from the Arduino device. */
                registeredAt: components["parameters"]["RegisteredAt"];
                /** @description Only use the date section of registered sensor readings from the Arduino device (registeredAt parameter). */
                dateOnly: components["parameters"]["DateOnly"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temperature deleted. */
            204: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: components["responses"]["ProblemDetailsResponse"];
            /** @description Forbidden. */
            403: components["responses"]["ProblemDetailsResponse"];
            /** @description Not Found. */
            404: components["responses"]["ProblemDetailsResponse"];
            /** @description To Many Requests. */
            429: components["responses"]["TooManyRequestsResponse"];
            /** @description Internal Server Error. */
            500: components["responses"]["ProblemDetailsResponse"];
        };
    };
}
